import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import { Document } from "mongoose";

// This is a Mongoose schema for a User entity.
@Schema()
export class User {
    // The unique identifier for the user, automatically generated by MongoDB.
    @Prop({ required: true })
    username: string;

    // The user's age, which is required.
    @Prop({ required: true, unique: true })
    email: string;
}

// The UserDocument type is a Mongoose document that includes the User schema.
export type UserDocument = User & Document;
// The UserSchema is created from the User class using Mongoose's SchemaFactory.
export const UserSchema = SchemaFactory.createForClass(User);